import "./globals.css";
import { Navbar } from "@/components/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <main className="flex min-h-screen flex-col bg-[#121212]">
          {children}
        </main>
      </body>
    </html>
  );
}
